export const actionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SET_CURRENCY : "SET_CURRENCY",
    TOGGLE_CURRENCY : "TOGGLE_CURRENCY",
    ARCHIVE_PRODUCT : "ARCHIVE_PRODUCT",
    UNARCHIVE_PRODUCT : "UNARCHIVE_PRODUCT",
    ADD_PRODUCT: "ADD_PRODUCT"
}